### ISSUE TITLE
Importing the qlik Engine into the controller

### ISSUE THREAD

**Issue by jonvitale** [axisgroup/qExt#2]
I apologize if this is kind of basic, but I'm having problems working through the answer.

In a standard extension, we do something like this to get the qlik engine
define(['qlik',...], function(qlik){ })

We can do something similar in your framework, like this:
export default window.define(['qlik'], function(qlik) {

But, the "qlik" object only seems to be within scope right there in the function. How do I get access to "qlik" in the controller, which is in a different file? In controller.js, this does not seem to work:

export default ['qlik', '$scope', '$element', function(qlik, $scope, $element){

Nor does using an import statement.

Any ideas?

**Comment by jabellizzi** [comment]
hey Jon. You should be able to load the qlik object into the controller module using require

You're controller.js file will look like this:
`var qlik = window.require('qlik');

export default ["$scope", "$element", function($scope, $element) {
  // qlik can be used in here
}]`

Hope this helps

**Comment by jonvitale** [comment]
Works completely. Thank you.
