### ISSUE TITLE
Update dependencies 

### ISSUE THREAD

**Issue by AnalyticsEarth** [axisgroup/qExt#8]
Can you update dependencies in your published NPM package version? I have a number of extensions all using this amazing package and without forking my own version is difficult to prevent vulnerability warnings that we get from a number of the package versions you are using.

thanks!

**Comment by jabellizzi** [comment]
Hi @AnalyticsEarth! I'm working on a major version release that will drop soon. I'll keep you posted once that's available

**Comment by jabellizzi** [comment]
@AnalyticsEarth qExt version 1.0 has been released! There have been some changes in how qext is now configured, so go check out the updates and documentation https://github.com/axisgroup/qExt

Let me know if you have any issues with the updates

**Comment by AnalyticsEarth** [comment]
Hi, thanks for this. when will v1 be pushed out to npm?

**Comment by jabellizzi** [comment]
Just published to npm now
